<?php

namespace DoctrineExoBundle\Repository;

/**
 * Author
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Author extends \Doctrine\ORM\EntityRepository
{
}
