<?php

namespace DoctrineExoBundle\Repository;

/**
 * BookRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BookRepository extends \Doctrine\ORM\EntityRepository
{

    public function findAllBooks()
    {

        // je crée un query builder pour faire une requête sql personnalisée en bdd
        $qb = $this->createQueryBuilder('u');

        // je crée ma requête pour sélectionner tous les éléments de ma table book (dont l'alias est u par convention)
        $requete = $qb->select('u')
                      ->getQuery();

        // je récupère le résultat de ma requête que je stocke dans une variable $resultats
        $resultats = $requete->getArrayResult();

        // je retourne la valeur de la variable $resultats pour quand je l'appelle dans une méthode je récupère le résultat de la variable
        return $resultats;

    }

    public function getBookByKind($kind)
    {

        $qb = $this->createQueryBuilder('u');

        $requete = $qb->select('u')
                      ->where('u.kind = :kind')
                      ->setParameter('kind', $kind)
                      ->getQuery();

        $resultats = $requete->getArrayResult();

        return $resultats;

    }


}
